import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Simulated clean sales dataset provided by the e-commerce client
raw_sales_data = {
    "Month": ["Jan", "Jan", "Feb", "Feb", "Mar", "Mar", "Apr", "Apr", "May", "May", "Jun", "Jun"],
    "Category": ["Coffee Beans", "Equipment", "Coffee Beans", "Equipment", "Coffee Beans", "Equipment", 
                 "Coffee Beans", "Equipment", "Coffee Beans", "Equipment", "Coffee Beans", "Equipment"],
    "Revenue": [12000, 8000, 14500, 7500, 19000, 11000, 16000, 13000, 22000, 9500, 25000, 15000],
    "Acquisition_Channel": ["Google Ads", "Email", "Social Media", "Google Ads", "Google Ads", "Social Media",
                           "Email", "Google Ads", "Social Media", "Email", "Google Ads", "Social Media"]
}

# Load data into a Pandas DataFrame
df = pd.DataFrame(raw_sales_data)

print("Starting Exploratory Data Analysis & Visualization...")

# --- CHART 1: MONTHLY REVENUE TRENDS BY CATEGORY ---
# Creating an interactive line chart to showcase monthly growth trajectories
fig_trends = px.line(
    df, 
    x="Month", 
    y="Revenue", 
    color="Category",
    markers=True,
    title="Monthly Revenue Growth Trends by Product Category (H1 2026)",
    labels={"Revenue": "Revenue ($)", "Month": "Timeline (2026)"},
    template="plotly_white"
)

# Polishing chart layout for executive presentations
fig_trends.update_layout(
    title_font_size=20,
    xaxis_title_font_size=14,
    yaxis_title_font_size=14,
    legend_title_text="Product Segments"
)

# Save the first chart as a high-resolution static PNG image for the board presentation
fig_trends.write_image("revenue_trends_by_category.png", scale=2)
print("✔ Chart 1 saved as 'revenue_trends_by_category.png'")


# --- CHART 2: ACQUISITION CHANNEL EFFICIENCY ---
# Aggregating total revenue generated by each marketing channel
channel_performance = df.groupby("Acquisition_Channel")["Revenue"].sum().reset_index()

# Creating a professional bar chart to compare marketing channel ROI
fig_channels = px.bar(
    channel_performance,
    x="Acquisition_Channel",
    y="Revenue",
    color="Acquisition_Channel",
    title="Total Revenue Generated by Acquisition Channel",
    labels={"Revenue": "Total Revenue ($)", "Acquisition_Channel": "Marketing Channel"},
    template="plotly_white",
    color_discrete_sequence=px.colors.qualitative.Pastel
)

# Customizing bars for cleaner presentation (sorting and text display)
fig_channels.update_layout(
    showlegend=False,
    title_font_size=20
)
fig_channels.update_traces(texttemplate='$%{y:,}', textposition='outside')

# Save the second chart as a high-resolution static PNG image
fig_channels.write_image("channel_efficiency_analysis.png", scale=2)
print("✔ Chart 2 saved as 'channel_efficiency_analysis.png'")

print("\n🚀 Visual Analytics Pipeline Completed Successfully!")